// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/codegraph/proto/file_element.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举类型定义
type Scope int32

const (
	Scope_SCOPE_UNDEFINED Scope = 0
	Scope_SCOPE_PUBLIC    Scope = 1
	Scope_SCOPE_PRIVATE   Scope = 2
	Scope_SCOPE_PROTECTED Scope = 3
	Scope_SCOPE_PACKAGE   Scope = 4
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNDEFINED",
		1: "SCOPE_PUBLIC",
		2: "SCOPE_PRIVATE",
		3: "SCOPE_PROTECTED",
		4: "SCOPE_PACKAGE",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNDEFINED": 0,
		"SCOPE_PUBLIC":    1,
		"SCOPE_PRIVATE":   2,
		"SCOPE_PROTECTED": 3,
		"SCOPE_PACKAGE":   4,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_codegraph_proto_file_element_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_pkg_codegraph_proto_file_element_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{0}
}

type RelationType int32

const (
	RelationType_RELATION_TYPE_UNDEFINED       RelationType = 0
	RelationType_RELATION_TYPE_DEFINITION      RelationType = 1
	RelationType_RELATION_TYPE_REFERENCE       RelationType = 2
	RelationType_RELATION_TYPE_INHERIT         RelationType = 3
	RelationType_RELATION_TYPE_IMPLEMENT       RelationType = 4
	RelationType_RELATION_TYPE_SUPER_CLASS     RelationType = 5
	RelationType_RELATION_TYPE_SUPER_INTERFACE RelationType = 6
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNDEFINED",
		1: "RELATION_TYPE_DEFINITION",
		2: "RELATION_TYPE_REFERENCE",
		3: "RELATION_TYPE_INHERIT",
		4: "RELATION_TYPE_IMPLEMENT",
		5: "RELATION_TYPE_SUPER_CLASS",
		6: "RELATION_TYPE_SUPER_INTERFACE",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNDEFINED":       0,
		"RELATION_TYPE_DEFINITION":      1,
		"RELATION_TYPE_REFERENCE":       2,
		"RELATION_TYPE_INHERIT":         3,
		"RELATION_TYPE_IMPLEMENT":       4,
		"RELATION_TYPE_SUPER_CLASS":     5,
		"RELATION_TYPE_SUPER_INTERFACE": 6,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_codegraph_proto_file_element_proto_enumTypes[1].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_pkg_codegraph_proto_file_element_proto_enumTypes[1]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{1}
}

// FileElementTable 文件元素表，简化版本
type FileElementTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Elements      []*BaseElement         `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileElementTable) Reset() {
	*x = FileElementTable{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileElementTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileElementTable) ProtoMessage() {}

func (x *FileElementTable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileElementTable.ProtoReflect.Descriptor instead.
func (*FileElementTable) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{0}
}

func (x *FileElementTable) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileElementTable) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FileElementTable) GetElements() []*BaseElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

// BaseElement 基础元素定义，对应 resolver.BaseElement
type BaseElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Scope         Scope                  `protobuf:"varint,3,opt,name=scope,proto3,enum=codegraphpb.Scope" json:"scope,omitempty"`
	IsDefinition  bool                   `protobuf:"varint,4,opt,name=is_definition,json=isDefinition,proto3" json:"is_definition,omitempty"`
	ElementType   ElementType            `protobuf:"varint,5,opt,name=element_type,json=elementType,proto3,enum=codegraphpb.ElementType" json:"element_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Range         []int32                `protobuf:"varint,7,rep,packed,name=range,proto3" json:"range,omitempty"`
	Relations     []*Relation            `protobuf:"bytes,8,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseElement) Reset() {
	*x = BaseElement{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseElement) ProtoMessage() {}

func (x *BaseElement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseElement.ProtoReflect.Descriptor instead.
func (*BaseElement) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{1}
}

func (x *BaseElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseElement) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BaseElement) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNDEFINED
}

func (x *BaseElement) GetIsDefinition() bool {
	if x != nil {
		return x.IsDefinition
	}
	return false
}

func (x *BaseElement) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_ELEMENT_TYPE_UNDEFINED
}

func (x *BaseElement) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BaseElement) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *BaseElement) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

// Relation 关系定义
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementName   string                 `protobuf:"bytes,1,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	ElementPath   string                 `protobuf:"bytes,2,opt,name=element_path,json=elementPath,proto3" json:"element_path,omitempty"`
	Range         []int32                `protobuf:"varint,3,rep,packed,name=range,proto3" json:"range,omitempty"`
	RelationType  RelationType           `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=codegraphpb.RelationType" json:"relation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_file_element_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_file_element_proto_rawDescGZIP(), []int{2}
}

func (x *Relation) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *Relation) GetElementPath() string {
	if x != nil {
		return x.ElementPath
	}
	return ""
}

func (x *Relation) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Relation) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNDEFINED
}

var File_pkg_codegraph_proto_file_element_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_file_element_proto_rawDesc = "" +
	"\n" +
	"&pkg/codegraph/proto/file_element.proto\x12\vcodegraphpb\x1a\x1fpkg/codegraph/proto/types.proto\"x\n" +
	"\x10FileElementTable\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x124\n" +
	"\belements\x18\x03 \x03(\v2\x18.codegraphpb.BaseElementR\belements\"\xa6\x02\n" +
	"\vBaseElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12(\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x12.codegraphpb.ScopeR\x05scope\x12#\n" +
	"\ris_definition\x18\x04 \x01(\bR\fisDefinition\x12;\n" +
	"\felement_type\x18\x05 \x01(\x0e2\x18.codegraphpb.ElementTypeR\velementType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12\x14\n" +
	"\x05range\x18\a \x03(\x05R\x05range\x123\n" +
	"\trelations\x18\b \x03(\v2\x15.codegraphpb.RelationR\trelations\"\xa6\x01\n" +
	"\bRelation\x12!\n" +
	"\felement_name\x18\x01 \x01(\tR\velementName\x12!\n" +
	"\felement_path\x18\x02 \x01(\tR\velementPath\x12\x14\n" +
	"\x05range\x18\x03 \x03(\x05R\x05range\x12>\n" +
	"\rrelation_type\x18\x04 \x01(\x0e2\x19.codegraphpb.RelationTypeR\frelationType*i\n" +
	"\x05Scope\x12\x13\n" +
	"\x0fSCOPE_UNDEFINED\x10\x00\x12\x10\n" +
	"\fSCOPE_PUBLIC\x10\x01\x12\x11\n" +
	"\rSCOPE_PRIVATE\x10\x02\x12\x13\n" +
	"\x0fSCOPE_PROTECTED\x10\x03\x12\x11\n" +
	"\rSCOPE_PACKAGE\x10\x04*\xe0\x01\n" +
	"\fRelationType\x12\x1b\n" +
	"\x17RELATION_TYPE_UNDEFINED\x10\x00\x12\x1c\n" +
	"\x18RELATION_TYPE_DEFINITION\x10\x01\x12\x1b\n" +
	"\x17RELATION_TYPE_REFERENCE\x10\x02\x12\x19\n" +
	"\x15RELATION_TYPE_INHERIT\x10\x03\x12\x1b\n" +
	"\x17RELATION_TYPE_IMPLEMENT\x10\x04\x12\x1d\n" +
	"\x19RELATION_TYPE_SUPER_CLASS\x10\x05\x12!\n" +
	"\x1dRELATION_TYPE_SUPER_INTERFACE\x10\x06B-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_file_element_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_file_element_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_file_element_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_file_element_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_file_element_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_file_element_proto_rawDesc), len(file_pkg_codegraph_proto_file_element_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_file_element_proto_rawDescData
}

var file_pkg_codegraph_proto_file_element_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_codegraph_proto_file_element_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_codegraph_proto_file_element_proto_goTypes = []any{
	(Scope)(0),               // 0: codegraphpb.Scope
	(RelationType)(0),        // 1: codegraphpb.RelationType
	(*FileElementTable)(nil), // 2: codegraphpb.FileElementTable
	(*BaseElement)(nil),      // 3: codegraphpb.BaseElement
	(*Relation)(nil),         // 4: codegraphpb.Relation
	(ElementType)(0),         // 5: codegraphpb.ElementType
}
var file_pkg_codegraph_proto_file_element_proto_depIdxs = []int32{
	3, // 0: codegraphpb.FileElementTable.elements:type_name -> codegraphpb.BaseElement
	0, // 1: codegraphpb.BaseElement.scope:type_name -> codegraphpb.Scope
	5, // 2: codegraphpb.BaseElement.element_type:type_name -> codegraphpb.ElementType
	4, // 3: codegraphpb.BaseElement.relations:type_name -> codegraphpb.Relation
	1, // 4: codegraphpb.Relation.relation_type:type_name -> codegraphpb.RelationType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_file_element_proto_init() }
func file_pkg_codegraph_proto_file_element_proto_init() {
	if File_pkg_codegraph_proto_file_element_proto != nil {
		return
	}
	file_pkg_codegraph_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_file_element_proto_rawDesc), len(file_pkg_codegraph_proto_file_element_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_file_element_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_file_element_proto_depIdxs,
		EnumInfos:         file_pkg_codegraph_proto_file_element_proto_enumTypes,
		MessageInfos:      file_pkg_codegraph_proto_file_element_proto_msgTypes,
	}.Build()
	File_pkg_codegraph_proto_file_element_proto = out.File
	file_pkg_codegraph_proto_file_element_proto_goTypes = nil
	file_pkg_codegraph_proto_file_element_proto_depIdxs = nil
}
