// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/codegraph/proto/symbol_definition.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SymbolDefinition 符号定义
type SymbolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Definitions   []*Definition          `protobuf:"bytes,3,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolDefinition) Reset() {
	*x = SymbolDefinition{}
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolDefinition) ProtoMessage() {}

func (x *SymbolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolDefinition.ProtoReflect.Descriptor instead.
func (*SymbolDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymbolDefinition) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SymbolDefinition) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

// Definition 定义详情
type Definition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Range         []int32                `protobuf:"varint,2,rep,packed,name=range,proto3" json:"range,omitempty"`
	ElementType   ElementType            `protobuf:"varint,3,opt,name=element_type,json=elementType,proto3,enum=codegraphpb.ElementType" json:"element_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_codegraph_proto_symbol_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP(), []int{1}
}

func (x *Definition) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Definition) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Definition) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_ELEMENT_TYPE_UNDEFINED
}

var File_pkg_codegraph_proto_symbol_definition_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_symbol_definition_proto_rawDesc = "" +
	"\n" +
	"+pkg/codegraph/proto/symbol_definition.proto\x12\vcodegraphpb\x1a\x1fpkg/codegraph/proto/types.proto\"}\n" +
	"\x10SymbolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x129\n" +
	"\vdefinitions\x18\x03 \x03(\v2\x17.codegraphpb.DefinitionR\vdefinitions\"s\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05range\x18\x02 \x03(\x05R\x05range\x12;\n" +
	"\felement_type\x18\x03 \x01(\x0e2\x18.codegraphpb.ElementTypeR\velementTypeB-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_symbol_definition_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_symbol_definition_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_symbol_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc), len(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_symbol_definition_proto_rawDescData
}

var file_pkg_codegraph_proto_symbol_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_codegraph_proto_symbol_definition_proto_goTypes = []any{
	(*SymbolDefinition)(nil), // 0: codegraphpb.SymbolDefinition
	(*Definition)(nil),       // 1: codegraphpb.Definition
	(ElementType)(0),         // 2: codegraphpb.ElementType
}
var file_pkg_codegraph_proto_symbol_definition_proto_depIdxs = []int32{
	1, // 0: codegraphpb.SymbolDefinition.definitions:type_name -> codegraphpb.Definition
	2, // 1: codegraphpb.Definition.element_type:type_name -> codegraphpb.ElementType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_symbol_definition_proto_init() }
func file_pkg_codegraph_proto_symbol_definition_proto_init() {
	if File_pkg_codegraph_proto_symbol_definition_proto != nil {
		return
	}
	file_pkg_codegraph_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc), len(file_pkg_codegraph_proto_symbol_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_symbol_definition_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_symbol_definition_proto_depIdxs,
		MessageInfos:      file_pkg_codegraph_proto_symbol_definition_proto_msgTypes,
	}.Build()
	File_pkg_codegraph_proto_symbol_definition_proto = out.File
	file_pkg_codegraph_proto_symbol_definition_proto_goTypes = nil
	file_pkg_codegraph_proto_symbol_definition_proto_depIdxs = nil
}
