// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/codegraph/proto/types.proto

package codegraphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ElementType 元素类型枚举，只包含核心类型
type ElementType int32

const (
	ElementType_UNDEFINED ElementType = 0
	ElementType_FUNCTION  ElementType = 1
	ElementType_METHOD    ElementType = 2
	ElementType_CALL      ElementType = 3
	ElementType_REFERENCE ElementType = 4
	ElementType_CLASS     ElementType = 5
	ElementType_INTERFACE ElementType = 6
	ElementType_VARIABLE  ElementType = 7
	ElementType_IMPORT    ElementType = 8
	ElementType_PACKAGE   ElementType = 9
)

// Enum value maps for ElementType.
var (
	ElementType_name = map[int32]string{
		0: "UNDEFINED",
		1: "FUNCTION",
		2: "METHOD",
		3: "CALL",
		4: "REFERENCE",
		5: "CLASS",
		6: "INTERFACE",
		7: "VARIABLE",
		8: "IMPORT",
		9: "PACKAGE",
	}
	ElementType_value = map[string]int32{
		"UNDEFINED": 0,
		"FUNCTION":  1,
		"METHOD":    2,
		"CALL":      3,
		"REFERENCE": 4,
		"CLASS":     5,
		"INTERFACE": 6,
		"VARIABLE":  7,
		"IMPORT":    8,
		"PACKAGE":   9,
	}
)

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}

func (x ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_codegraph_proto_types_proto_enumTypes[0].Descriptor()
}

func (ElementType) Type() protoreflect.EnumType {
	return &file_pkg_codegraph_proto_types_proto_enumTypes[0]
}

func (x ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementType.Descriptor instead.
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_codegraph_proto_types_proto_rawDescGZIP(), []int{0}
}

var File_pkg_codegraph_proto_types_proto protoreflect.FileDescriptor

const file_pkg_codegraph_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/codegraph/proto/types.proto\x12\vcodegraphpb*\x90\x01\n" +
	"\vElementType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\f\n" +
	"\bFUNCTION\x10\x01\x12\n" +
	"\n" +
	"\x06METHOD\x10\x02\x12\b\n" +
	"\x04CALL\x10\x03\x12\r\n" +
	"\tREFERENCE\x10\x04\x12\t\n" +
	"\x05CLASS\x10\x05\x12\r\n" +
	"\tINTERFACE\x10\x06\x12\f\n" +
	"\bVARIABLE\x10\a\x12\n" +
	"\n" +
	"\x06IMPORT\x10\b\x12\v\n" +
	"\aPACKAGE\x10\tB-Z+pkg/codegraph/proto/codegraphpb;codegraphpbb\x06proto3"

var (
	file_pkg_codegraph_proto_types_proto_rawDescOnce sync.Once
	file_pkg_codegraph_proto_types_proto_rawDescData []byte
)

func file_pkg_codegraph_proto_types_proto_rawDescGZIP() []byte {
	file_pkg_codegraph_proto_types_proto_rawDescOnce.Do(func() {
		file_pkg_codegraph_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_types_proto_rawDesc), len(file_pkg_codegraph_proto_types_proto_rawDesc)))
	})
	return file_pkg_codegraph_proto_types_proto_rawDescData
}

var file_pkg_codegraph_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_codegraph_proto_types_proto_goTypes = []any{
	(ElementType)(0), // 0: codegraphpb.ElementType
}
var file_pkg_codegraph_proto_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_codegraph_proto_types_proto_init() }
func file_pkg_codegraph_proto_types_proto_init() {
	if File_pkg_codegraph_proto_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_codegraph_proto_types_proto_rawDesc), len(file_pkg_codegraph_proto_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_codegraph_proto_types_proto_goTypes,
		DependencyIndexes: file_pkg_codegraph_proto_types_proto_depIdxs,
		EnumInfos:         file_pkg_codegraph_proto_types_proto_enumTypes,
	}.Build()
	File_pkg_codegraph_proto_types_proto = out.File
	file_pkg_codegraph_proto_types_proto_goTypes = nil
	file_pkg_codegraph_proto_types_proto_depIdxs = nil
}
