// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: codebase_syncer.proto

package codebase_syncer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token 共享请求（，加密存储）
// 共享 AccessToken 请求（包含 server_endpoint）
type ShareAccessTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                   // 客户ID
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`          // Token
	ServerEndpoint string                 `protobuf:"bytes,3,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"` // 云端服务端点
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShareAccessTokenRequest) Reset() {
	*x = ShareAccessTokenRequest{}
	mi := &file_codebase_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareAccessTokenRequest) ProtoMessage() {}

func (x *ShareAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codebase_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*ShareAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_codebase_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *ShareAccessTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ShareAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ShareAccessTokenRequest) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

// 共享 Token 响应
type ShareAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareAccessTokenResponse) Reset() {
	*x = ShareAccessTokenResponse{}
	mi := &file_codebase_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareAccessTokenResponse) ProtoMessage() {}

func (x *ShareAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codebase_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*ShareAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_codebase_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *ShareAccessTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShareAccessTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 注册工作区同步
type RegisterSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                // 客户ID
	WorkspacePath string                 `protobuf:"bytes,2,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"` // 工作区路径
	WorkspaceName string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"` // 工作区名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSyncRequest) Reset() {
	*x = RegisterSyncRequest{}
	mi := &file_codebase_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSyncRequest) ProtoMessage() {}

func (x *RegisterSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codebase_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSyncRequest.ProtoReflect.Descriptor instead.
func (*RegisterSyncRequest) Descriptor() ([]byte, []int) {
	return file_codebase_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSyncRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterSyncRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *RegisterSyncRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

// 注册工作区同步响应
type RegisterSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSyncResponse) Reset() {
	*x = RegisterSyncResponse{}
	mi := &file_codebase_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSyncResponse) ProtoMessage() {}

func (x *RegisterSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codebase_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSyncResponse.ProtoReflect.Descriptor instead.
func (*RegisterSyncResponse) Descriptor() ([]byte, []int) {
	return file_codebase_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 注销工作区同步
type UnregisterSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                // 客户ID
	WorkspacePath string                 `protobuf:"bytes,2,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"` // 工作区路径
	WorkspaceName string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"` // 工作区名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterSyncRequest) Reset() {
	*x = UnregisterSyncRequest{}
	mi := &file_codebase_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterSyncRequest) ProtoMessage() {}

func (x *UnregisterSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codebase_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterSyncRequest.ProtoReflect.Descriptor instead.
func (*UnregisterSyncRequest) Descriptor() ([]byte, []int) {
	return file_codebase_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterSyncRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UnregisterSyncRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *UnregisterSyncRequest) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

var File_codebase_syncer_proto protoreflect.FileDescriptor

const file_codebase_syncer_proto_rawDesc = "" +
	"\n" +
	"\x15codebase_syncer.proto\x12\x0fcodebase_syncer\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\x17ShareAccessTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12'\n" +
	"\x0fserver_endpoint\x18\x03 \x01(\tR\x0eserverEndpoint\"N\n" +
	"\x18ShareAccessTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x13RegisterSyncRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0eworkspace_path\x18\x02 \x01(\tR\rworkspacePath\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\"J\n" +
	"\x14RegisterSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x82\x01\n" +
	"\x15UnregisterSyncRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0eworkspace_path\x18\x02 \x01(\tR\rworkspacePath\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName2\xa5\x02\n" +
	"\vSyncService\x12[\n" +
	"\fRegisterSync\x12$.codebase_syncer.RegisterSyncRequest\x1a%.codebase_syncer.RegisterSyncResponse\x12P\n" +
	"\x0eUnregisterSync\x12&.codebase_syncer.UnregisterSyncRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x10ShareAccessToken\x12(.codebase_syncer.ShareAccessTokenRequest\x1a).codebase_syncer.ShareAccessTokenResponseB\x14Z\x12./;codebase_syncerb\x06proto3"

var (
	file_codebase_syncer_proto_rawDescOnce sync.Once
	file_codebase_syncer_proto_rawDescData []byte
)

func file_codebase_syncer_proto_rawDescGZIP() []byte {
	file_codebase_syncer_proto_rawDescOnce.Do(func() {
		file_codebase_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codebase_syncer_proto_rawDesc), len(file_codebase_syncer_proto_rawDesc)))
	})
	return file_codebase_syncer_proto_rawDescData
}

var file_codebase_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_codebase_syncer_proto_goTypes = []any{
	(*ShareAccessTokenRequest)(nil),  // 0: codebase_syncer.ShareAccessTokenRequest
	(*ShareAccessTokenResponse)(nil), // 1: codebase_syncer.ShareAccessTokenResponse
	(*RegisterSyncRequest)(nil),      // 2: codebase_syncer.RegisterSyncRequest
	(*RegisterSyncResponse)(nil),     // 3: codebase_syncer.RegisterSyncResponse
	(*UnregisterSyncRequest)(nil),    // 4: codebase_syncer.UnregisterSyncRequest
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_codebase_syncer_proto_depIdxs = []int32{
	2, // 0: codebase_syncer.SyncService.RegisterSync:input_type -> codebase_syncer.RegisterSyncRequest
	4, // 1: codebase_syncer.SyncService.UnregisterSync:input_type -> codebase_syncer.UnregisterSyncRequest
	0, // 2: codebase_syncer.SyncService.ShareAccessToken:input_type -> codebase_syncer.ShareAccessTokenRequest
	3, // 3: codebase_syncer.SyncService.RegisterSync:output_type -> codebase_syncer.RegisterSyncResponse
	5, // 4: codebase_syncer.SyncService.UnregisterSync:output_type -> google.protobuf.Empty
	1, // 5: codebase_syncer.SyncService.ShareAccessToken:output_type -> codebase_syncer.ShareAccessTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codebase_syncer_proto_init() }
func file_codebase_syncer_proto_init() {
	if File_codebase_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codebase_syncer_proto_rawDesc), len(file_codebase_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codebase_syncer_proto_goTypes,
		DependencyIndexes: file_codebase_syncer_proto_depIdxs,
		MessageInfos:      file_codebase_syncer_proto_msgTypes,
	}.Build()
	File_codebase_syncer_proto = out.File
	file_codebase_syncer_proto_goTypes = nil
	file_codebase_syncer_proto_depIdxs = nil
}
